/*
 * @adonisjs/core
 *
 * (c) AdonisJS
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { test } from '@japa/runner'
import Codegen from '../../commands/codegen.ts'
import { AceFactory } from '../../factories/core/ace.ts'
import { indexEntities } from '../../src/assembler_hooks/index_entities.ts'
import { setupTypeScriptProject } from '../helpers.ts'

test.group('Codegen command', () => {
  test('show error when assembler is not installed', async ({ assert, fs }) => {
    await setupTypeScriptProject()

    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => {
        if (filePath === '@adonisjs/assembler/index_generator') {
          return import(new URL(filePath, fs.baseUrl).href)
        }

        return import(filePath)
      },
    })
    await ace.app.init()
    await ace.app.boot()
    ace.ui.switchMode('raw')

    const command = await ace.create(Codegen, [])
    await command.exec()

    assert.equal(command.exitCode, 1)
    assert.lengthOf(ace.ui.logger.getLogs(), 1)
    assert.equal(ace.ui.logger.getLogs()[0].stream, 'stderr')
    assert.match(ace.ui.logger.getLogs()[0].message, /Cannot find package "@adonisjs\/assembler/)
  })

  test('generate route types and index files', async ({ assert, fs }) => {
    await fs.create('app/controllers/users_controller.ts', '')
    await fs.create('app/events/user_registered.ts', '')
    await fs.create('app/listeners/send_welcome_email.ts', '')
    await setupTypeScriptProject()

    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => import(filePath),
    })

    ace.app.rcFile.hooks = {
      init: [indexEntities()],
    }

    await ace.app.init()
    await ace.app.boot()

    const router = await ace.app.container.make('router')
    router.get('/users', () => 'ok')

    ace.ui.switchMode('raw')

    const command = await ace.create(Codegen, [])
    await command.exec()

    assert.equal(command.exitCode, 0)
    assert.deepEqual(ace.ui.logger.getLogs(), [
      {
        message: '[ blue(info) ] codegen: created 3 file(s)',
        stream: 'stdout',
      },
      {
        message: '[ green(success) ] Codegen files generated',
        stream: 'stdout',
      },
    ])
    assert.snapshot(await fs.contents('.adonisjs/server/controllers.ts')).matchInline(`
      "/**
       * This file is automatically generated.
       * DO NOT EDIT manually
       */

      export const controllers = {
        Users: () => import('#controllers/users_controller'),
      }
      "
    `)
    assert.snapshot(await fs.contents('.adonisjs/server/events.ts')).matchInline(`
      "/**
       * This file is automatically generated.
       * DO NOT EDIT manually
       */

      import UserRegistered from '#events/user_registered'

      export const events = {
        UserRegistered: UserRegistered,
      }
      "
    `)
    await assert.fileExists('.adonisjs/server/routes.d.ts')
    await assert.fileContains('.adonisjs/server/routes.d.ts', ['export type ScannedRoutes = {'])
    await assert.fileExists('.adonisjs/server/routes.json')
  })

  test('only generate index files for enabled entities', async ({ assert, fs }) => {
    await fs.create('app/controllers/users_controller.ts', '')
    await setupTypeScriptProject()

    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => import(filePath),
    })

    ace.app.rcFile.hooks = {
      init: [
        indexEntities({
          events: { enabled: false },
          listeners: { enabled: false },
        }),
      ],
    }

    await ace.app.init()
    await ace.app.boot()
    ace.ui.switchMode('raw')

    const command = await ace.create(Codegen, [])
    await command.exec()

    assert.equal(command.exitCode, 0)
    await assert.fileExists('.adonisjs/server/controllers.ts')
    await assert.fileNotExists('.adonisjs/server/events.ts')
    await assert.fileNotExists('.adonisjs/server/listeners.ts')
  })
})
