/*
 * @adonisjs/core
 *
 * (c) AdonisJS
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { basename } from 'node:path'
import { fileURLToPath } from 'node:url'
import { test } from '@japa/runner'
import Serve from '../../commands/serve.ts'
import { AceFactory } from '../../factories/core/ace.ts'
import { setupTypeScriptProject } from '../helpers.ts'
import { indexEntities } from '../../src/assembler_hooks/index_entities.ts'
import { computeWorktreePort } from '../../src/helpers/worktree.ts'

const sleep = (duration: number) => new Promise((resolve) => setTimeout(resolve, duration))

test.group('Serve command', () => {
  test('show error when assembler is not installed', async ({ assert, fs }) => {
    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => {
        if (filePath === '@adonisjs/assembler') {
          return import(new URL(filePath, fs.baseUrl).href)
        }

        return import(filePath)
      },
    })
    await ace.app.init()
    ace.ui.switchMode('raw')

    const command = await ace.create(Serve, ['--no-clear'])
    await command.exec()
    await sleep(600)

    assert.equal(command.exitCode, 1)
    assert.lengthOf(ace.ui.logger.getLogs(), 1)
    assert.equal(ace.ui.logger.getLogs()[0].stream, 'stderr')
    assert.match(ace.ui.logger.getLogs()[0].message, /Cannot find package "@adonisjs\/assembler/)
  })

  test('fail when bin/server.js file is missing', async ({ assert, fs, cleanup }) => {
    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => {
        if (filePath === 'typescript') {
          return import(new URL(filePath, fs.baseUrl).href)
        }

        return import(filePath)
      },
    })
    await ace.app.init()
    ace.ui.switchMode('raw')

    const command = await ace.create(Serve, ['--no-clear'])
    cleanup(() => command.devServer.close())
    await command.exec()

    await sleep(600)

    assert.equal(command.exitCode, 1)
  })

  test('fail in watch mode when tsconfig file is missing', async ({ assert, fs, cleanup }) => {
    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => {
        return import(filePath)
      },
    })
    await ace.app.init()
    ace.ui.switchMode('raw')

    const command = await ace.create(Serve, ['--no-clear'])
    cleanup(() => command.devServer.close())
    command.watch = true
    await command.exec()

    await sleep(600)

    assert.equal(command.exitCode, 1)
  })

  test('correctly pass hooks to the DevServer', async ({ assert, fs, cleanup }) => {
    assert.plan(1)
    await fs.create('bin/server.ts', `process.send({ isAdonisJS: true, environment: 'web' });`)

    await setupTypeScriptProject()

    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => import(filePath),
    })

    ace.app.rcFile.hooks = {
      devServerStarted: [
        async () => ({
          default: async () => {
            assert.isTrue(true)
          },
        }),
      ],
    }

    ace.ui.switchMode('raw')

    const command = await ace.create(Serve, ['--no-clear'])
    cleanup(() => command.devServer.close())
    await command.exec()
    await sleep(1200)
  })

  test('error if --hmr and --watch are used together', async ({ assert, fs }) => {
    await fs.create('node_modules/ts-node-maintained/esm.js', '')

    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => import(filePath),
    })

    ace.ui.switchMode('raw')

    const command = await ace.create(Serve, ['--hmr', '--watch', '--no-clear'])
    await command.exec()

    assert.equal(command.exitCode, 1)
    assert.lengthOf(ace.ui.logger.getLogs(), 1)
    assert.equal(ace.ui.logger.getLogs()[0].stream, 'stderr')
    assert.match(ace.ui.logger.getLogs()[0].message, /Cannot use --watch and --hmr flags together/)
  })

  test('generate barrel file for controllers, events and listeners', async ({
    assert,
    fs,
    cleanup,
  }) => {
    await fs.create('bin/server.ts', `process.send({ isAdonisJS: true, environment: 'web' });`)
    await setupTypeScriptProject()

    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => import(filePath),
    })

    ace.app.rcFile.hooks = {
      init: [indexEntities()],
    }

    ace.ui.switchMode('raw')

    const command = await ace.create(Serve, ['--no-clear'])
    cleanup(() => command.devServer.close())
    await command.exec()

    assert.snapshot(await fs.contents('.adonisjs/server/controllers.ts')).matchInline(`
      "/**
       * This file is automatically generated.
       * DO NOT EDIT manually
       */

      export const controllers = {}
      "
    `)
    assert.snapshot(await fs.contents('.adonisjs/server/events.ts')).matchInline(`
      "/**
       * This file is automatically generated.
       * DO NOT EDIT manually
       */

      export const events = {}
      "
    `)
    assert.snapshot(await fs.contents('.adonisjs/server/listeners.ts')).matchInline(`
      "/**
       * This file is automatically generated.
       * DO NOT EDIT manually
       */

      export const listeners = {}
      "
    `)
  })

  test('disable listeners and events barrel file generation', async ({ assert, fs, cleanup }) => {
    await fs.create('bin/server.ts', `process.send({ isAdonisJS: true, environment: 'web' });`)
    await setupTypeScriptProject()

    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => import(filePath),
    })

    ace.app.rcFile.hooks = {
      init: [indexEntities({ events: { enabled: false }, listeners: { enabled: false } })],
    }

    ace.ui.switchMode('raw')

    const command = await ace.create(Serve, ['--no-clear'])
    cleanup(() => command.devServer.close())
    await command.exec()

    assert.snapshot(await fs.contents('.adonisjs/server/controllers.ts')).matchInline(`
      "/**
       * This file is automatically generated.
       * DO NOT EDIT manually
       */

      export const controllers = {}
      "
    `)
    await assert.fileNotExists('.adonisjs/server/events.ts')
    await assert.fileNotExists('.adonisjs/server/listeners.ts')
  })

  test('use a deterministic port when running inside a git worktree', async ({
    assert,
    fs,
    cleanup,
  }) => {
    await fs.create('bin/server.ts', `process.send({ isAdonisJS: true, environment: 'web' });`)
    await fs.create('.git', 'gitdir: /path/to/main/.git/worktrees/feature-login\n')
    await fs.create('.env', 'PORT=3333\n')
    await setupTypeScriptProject()

    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => import(filePath),
    })

    ace.ui.switchMode('raw')

    const originalPort = process.env.PORT
    cleanup(() => {
      if (originalPort === undefined) {
        delete process.env.PORT
      } else {
        process.env.PORT = originalPort
      }
    })

    const command = await ace.create(Serve, ['--no-clear'])
    cleanup(() => command.devServer.close())
    await command.exec()
    await sleep(600)

    const worktreeName = basename(fileURLToPath(fs.baseUrl))
    const expectedPort = computeWorktreePort(worktreeName, 3333)
    assert.equal(Number(process.env.PORT), expectedPort)
    assert.match(ace.ui.logger.getLogs()[0].message, new RegExp(`Using worktree "${worktreeName}"`))
  })

  test('do not override the port when not inside a git worktree', async ({ assert, fs }) => {
    const ace = await new AceFactory().make(fs.baseUrl, {
      importer: (filePath) => import(filePath),
    })

    ace.ui.switchMode('raw')

    const command = await ace.create(Serve, ['--no-clear'])
    await command.exec()
    await sleep(600)

    assert.isUndefined(process.env.PORT)
  })
})
