name: checks
on:
  - push
  - pull_request
  - workflow_call
jobs:
  test:
    uses: adonisjs/core/.github/workflows/test.yml@7.x
    with:
      install-pnpm: true

  lint:
    uses: adonisjs/.github/.github/workflows/lint.yml@next

  typecheck:
    uses: adonisjs/.github/.github/workflows/typecheck.yml@next
