name: checks
on:
  - push
  - pull_request
  - workflow_call
permissions:
  contents: read

jobs:
  test:
    uses: adonisjs/core/.github/workflows/test.yml@0348a3b448fe91194d8ccf62d481b38ac9189176 # 7.x
    with:
      install-pnpm: true

  lint:
    uses: adonisjs/.github/.github/workflows/lint.yml@7eeb68b240344601ced8ef4fbe0b4dd31df0760b # main

  typecheck:
    uses: adonisjs/.github/.github/workflows/typecheck.yml@7eeb68b240344601ced8ef4fbe0b4dd31df0760b # main
