on:
  workflow_call:
    inputs:
      disable-windows:
        description: Disable running tests on Windows
        type: boolean
        default: false
        required: false
      install-pnpm:
        description: Install pnpm before running tests
        type: boolean
        default: false
        required: false

permissions:
  contents: read

jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/krypton', 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        if: ${{ inputs.install-pnpm }}
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  test_windows:
    if: ${{ !inputs.disable-windows }}
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ['lts/krypton', 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        if: ${{ inputs.install-pnpm }}
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
